[package]
name = "holodeque"
version = "0.1.0"
edition = "2018"

[dependencies.serde]
optional = true
version = "1"
default-features = false

[dev-dependencies.serde_test]
version = "1"

[features]
default = ["std"]
std = []
